allowBuilds:
  '@apollo/protobufjs': true
minimumReleaseAgeExclude:
  - '@nestjs/core@11.2.4'
  - '@nestjs/platform-express@11.2.4'
  - '@nestjs/platform-fastify@11.2.4'
  - '@nestjs/platform-socket.io@11.2.4'
  - '@nestjs/platform-ws@11.2.4'
  - '@nestjs/testing@11.2.4'
  - '@nestjs/websockets@11.2.4'
  - '@nestjs/common@11.2.4'
