export const THROTTLER_LIMIT = 'THROTTLER:LIMIT';
export const THROTTLER_TTL = 'THROTTLER:TTL';
export const THROTTLER_TRACKER = 'THROTTLER:TRACKER';
export const THROTTLER_KEY_GENERATOR = 'THROTTLER:KEY_GENERATOR';
export const THROTTLER_OPTIONS = 'THROTTLER:MODULE_OPTIONS';
export const THROTTLER_SKIP = 'THROTTLER:SKIP';
